### ISSUE TITLE
NPM package should be named 'grunt-contrib-lesslint'

### ISSUE THREAD

**Issue by alexreg** [jgable/grunt-lesslint#101]
Just out of convention. That's all. :-)

**Comment by jgable** [comment]
I don't get grandfathered in since this plugin has been around before that convention? 👴

**Comment by alexreg** [comment]
Haha, maybe. Feel free to ignore. :-)

**Comment by shinnn** [comment]
> NPM package should be named 'grunt-contrib-lesslint'

Please don't do that.

https://gruntjs.com/creating-plugins#naming-your-task

> The "grunt-contrib" namespace is reserved for tasks maintained by the Grunt team, please name your task something appropriate that avoids that naming scheme.

**Comment by alexreg** [comment]
Oh right. I read they should all be "grunt-contrib"-prefixed, but my bad. Ignore this please.
