### ISSUE TITLE
CLI please

### ISSUE THREAD

**Issue by mcandre** [jgable/grunt-lesslint#50]
Could we please have a command line interface in addition to the grunt task? It would be nice to be able to `lesslint` `.less` files in a non-NPM project.

**Comment by Rodrigo-Ludgero** [comment]
+1 add options .csslintrc or lesslintrc
	options: {
		csslintrc: '.csslintrc' or lesslintrc: '.lesslintrc' 
	}
it would be great to have this option, thanks in advance.

**Comment by davidparsson** [comment]
@Rodrigo-Ludgero, please create a new issue for new feature requests.

**Comment by Rodrigo-Ludgero** [comment]
@davidparsson ok, thx for the support.

**Comment by jgable** [comment]
I think it's safe to say this is covered by other libraries at this point. At any rate, it's not something I will have the bandwidth to do so I'm closing this issue.
