### ISSUE TITLE
less options are not passed to the less parser properly

### ISSUE THREAD

**Issue by CoffeeAndCode** [jgable/grunt-lesslint#52]
The full options hash is passed right now instead of just the `less` section (if present). I believe this change was introduced in commit 30e4162.

**Comment by jgable** [comment]
Gonna wait on one more PR to land and publish a new version that might affect this.  If it isn't fixed I'll take some time to make it work this weekend.

**Comment by jirihelmich** [comment]
Oh. That's why I spent last 30 minutes checking if my files are still there and paths are correct. :-1: for leaving such a bug in production version :(

But thanks for the project anyway.

**Comment by jgable** [comment]
@jirihelmich Thanks for the backhanded appreciation of the project.

I've merged the other PR manually and published as 1.1.14.  I'll close this issue for now, if someone runs into it again I will re-open.

**Comment by jirihelmich** [comment]
I definitely meant no disrespect, I sincerely appreciate any project, which is publicly available and can be easily used.

Thanks for merging the PR.
