### ISSUE TITLE
Possiblity to mute certain errors?

### ISSUE THREAD

**Issue by mhaamann** [jgable/grunt-lesslint#57]
I am getting the following error:
```
variable @base_color is undefined
```

1. Is it possible to define the variable from the gruntfile?
2. Or can i somehow include a less file with the missing variable?
3. Can i mute this type of error? It stops the csslinter from linting even with the --force flag.

I tried the following:
```javascript
lesslint: {
      app: {
        src: 'sites/all/modules/custom/kw_newsletter/css/kw_newsletter_wysiwyg.css.less',
        options: {
          less: {
            modifyVars: {base_color: 'red'},
            paths: ['sites/all/modules/custom/kw_base/lint_helper']
          }
        }
      }
    }
```
In the lint_helper folder i have a helper.less file that defines the base_color variable.

**Comment by jgable** [comment]
Can you put together an example repo I can clone down to reproduce this?  Otherwise, I'm afraid I'll spend time on it going back and forth and not be able to reproduce it locally.
