### ISSUE TITLE
Getting errors from imports without specifying the imports

### ISSUE THREAD

**Issue by dontwork** [jgable/grunt-lesslint#61]
less file being linted:
`@import "_variables.less";
@import "_bootstrap.less";
@import "_fonts.less";

.hello {
  font-size: 10px;
  font-size: 11px
  background: red;
}`

lines relating to lesslint in the gruntfile:

`lesslint: {
  src: ['less/style.less']
}`

output:

`Running "lesslint:src" (lesslint) task
less/style.less (5)
Expected end of value but found 'background'. Properties should be known (listed in CSS3 specification) or be a vendor-prefixed property. (known-properties)
>> less/style.less [Line 7, Column 3]:	 font-size: 11px
Too many !important declarations (63), try to use less than 10 to avoid specificity issues. Be careful when using !important declaration (important)
Too many font-size declarations (64), abstraction needed. Checks the number of font-size declarations. (font-sizes)
Too many floats (28), you're probably using them for layout. Consider using a grid system instead. This rule tests if the float property is used too many times (floats)
You have 6 h1s, 5 h2s, 5 h3s, 4 h4s, 3 h5s, 3 h6s defined in this stylesheet. Headings should be defined only once. (unique-headings)

>> 5 lint errors in 1 file.
Warning: Task "lesslint:src" failed. Use --force to continue.`

Im guessing the warnings it is showing here are from the imports in style.less despite all issues on this state that imports must be specified in order to be linted.

Any assistance on this?

**Comment by jgable** [comment]
Do you have a repo I can clone down and take a look at to confirm?  If not,
would you mind creating a simple one so I don't chase the wrong thing down?

**Comment by dontwork** [comment]
I will be able to get you a repo in a day or 2. All I'm doing is linting an
less file which has imports. The grunt task then shows the 'rollup' errors
in terminal. If I do not include the bootstrap import it does not have the
errors so they are definitely caused by the bootstrap.less file being
imported.

Cheers. Great plugin apart from this minor issue!

**Comment by dontwork** [comment]
https://github.com/dontwork/lessLintTestRepo

**Comment by jgable** [comment]
Those are what are called "rollup" errors.  They aren't necessarily specific to a certain file, but the whole aggregate of the generated stylesheet.

```
{ type: 'warning',
  rollup: true,
  message: 'Too many !important declarations (63), try to use less than 10 to avoid specificity issues.',
  rule: 
   { id: 'important',
     name: 'Disallow !important',
     desc: 'Be careful when using !important declaration',
     browsers: 'All',
     init: [Function] } }
```

There is no filename associated with the error so we have no way of telling whether it's in an import file or not.  I started showing these with PR #34 since we were just silently ignoring them before.

You can ignore the errors explicitly by adding a csslint option

```
lesslint: {
  src: ['less/style.less'],
  options: {
    csslint: {
      important: false,
      "font-sizes": false,
      floats: false,
      "unique-headings": false
    }
  }
}
```

I see a couple options from here that this task could do, but I'm hesitant to jump right in on either:

0. Ignore rollup warnings in this task (they are just warnings after all)
0. Add a config option to treat these as errors optionally (combined with 1)

I'm going to close for now, since this isn't something we will be fixing for the time being.

**Comment by dontwork** [comment]
If I ignore those lint warnings won't it then ignore those warnings in my own style sheets? I wouldn't want that. Is there a setting to ignore the 'rollup' warnings and have them not appear. For this task to pass in a build I would have to permanently run it with force.

**Comment by jgable** [comment]
I looked for something on the CSS lint site that would disable rollups, but I could not find it.  Ignoring rollups should be something that they support upstream and we pass to them as options.

If they are adamant about not providing a way to ignore rollups, then I'll consider ignoring and erroring behind a config option.

**Comment by dontwork** [comment]
Just to confirm then, the only option is to ignore the warnings from the bootstrap.less import at the expense of not seeing them for my own style sheets?
