### ISSUE TITLE
Load options through the .csslintrc file in the current working directory

### ISSUE THREAD

**Issue by Rodrigo-Ludgero** [jgable/grunt-lesslint#71]
Hello guys, 
i have a improvement suggestion.
Would it be possible add in the settings, options like this: ".csslintrc" or ".lesslintrc" or both.

```JavaScript
options: {
      csslintrc: '.csslintrc', 
      lesslintrc: '.lesslintrc'
}
```

it would be great to have this option, thanks in advance.

**Comment by davidparsson** [comment]
It is possible to achieve this today without any changes. Configure your Gruntfile.js like this:

```JavaScript
lesslint: {
  // ...
  options: {
    csslint: grunt.file.readJSON(".csslintrc")
  }
}
```

If you'd like grunt-lesslint to handle the file parsing, pull requests are welcome.

**Comment by davidparsson** [comment]
Another option is to define it in the csslint task configuration:

```JavaScript
csslint: {
  options: {
    csslintrc: ".csslintrc"
  }
},
lesslint: {
  // Targets ...
}
```

**Comment by davidparsson** [comment]
This is actually possible by using undocumented configuration values:

```JavaScript
options: {
  csslint: {
    csslintrc: '.csslintrc'
  }
}
```

I'll add a note about it in the readme file.

**Comment by Rodrigo-Ludgero** [comment]
Ok @davidparsson, thank you very much for your feedback :)
