### ISSUE TITLE
Not Validating

### ISSUE THREAD

**Issue by jwilkinson** [jgable/grunt-lesslint#89]
I run https://shop.loblaws.ca/media/stylesheets/loblaw/main.css through http://www.stylestats.org/results/cJ62w6hajf and through gruntless and for example I have the rule for no useage of IDs and the lint passes, yet there are 153 IDs in the file.

I don't think this is actually working on all rules.

**Comment by davidparsson** [comment]
The rule `ids` disallows IDs in selectors, not IDs in general: https://github.com/CSSLint/csslint/wiki/disallow-ids-in-selectors

Dose that explain this? If not, please clarify.

**Comment by jwilkinson** [comment]
See Rule Details where it gives examples of warnings, using just an ID should throw a warning.

https://github.com/CSSLint/csslint/wiki/disallow-ids-in-selectors#rule-details

**Comment by davidparsson** [comment]
Yes, right. I don't think this plugin currently supports warnings at all. @jgable, please confirm.

If you want that feature, please create a new issue stating this more clearly. I'd be happy to merge a pull request implementing that.

**Comment by jwilkinson** [comment]
What's wrong with this issue lol. Process for the sake of process? And
there might be other properties also not working.

**Comment by davidparsson** [comment]
For the sake of clarity, so that the first post clearly describes the
actual issue.

tors 3 mars 2016 kl 13:24 skrev James Wilkinson <notifications@github.com>:

> What's wrong with this issue lol. Process for the sake of process? And
> there might be other properties also not working.
>

**Comment by jwilkinson** [comment]
That's merely process for the sake of process you've identified what the
issue I am facing is after I came to you with a problem.

You don't go back to a client when they tell you somethings broken to tell
them to send you a new ticket. You can make one on your own if you so need
it or you could fix the issue as discovered in this issue.

Cheers

**Comment by davidparsson** [comment]
I'm actually quite offended by your response. There's no process, I just try to make this as easy as possible for anyone who might be interested in fixing this issue. I do this in my spare time and I have no personal interest in getting this feature implemented. Finally, as long as you're making requests without offering me your money or your time, you're not my client.

**Comment by jwilkinson** [comment]
A problem was presented for someone to solve. You found the root cause and
refused to fix it.

Congratulations on contributing to the demise of your pet project. We will
take your code out of our application.

**Comment by davidparsson** [comment]
I have created #90. I hope that issue describes the use case you're looking fore.

**Comment by jwilkinson** [comment]
Appreciated.

**Comment by jgable** [comment]
I was going to say something, but it's just not worth it.  The @jwilkinson's of the world are [killing the open source community](https://medium.com/@sebmck/2015-in-review-51ac7035e272#.2h06hu7sg).  Thinks I'm a client, has never paid me money for the software I write, or even sent me a birthday card.

Has made no significant contribution to any open source project that I can see.  Makes money making websites for credit report companies off my software, then comes and has an attitude about process when we are trying to clarify the issue.

I can't even... I just, can't even.

**Comment by davidparsson** [comment]
Thanks for your comment, @jgable. It actually means a lot. This single conversation made me so upset yesterday that I seriously considered stopping being an active member of the open source community, because it's just not worth taking shit like this. But I've decided to stay.

And by the way, @jwilkinson. This is much more of @jgable's "pet project" than mine. I'm just some random guy on the internet who thought that grunt-lesslint lacked a few features and decided to help out. Can you imagine that?

**Comment by davidparsson** [comment]
#90 is implemented and released in v3.1.0
