### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by GMartigny** [jgable/grunt-lesslint#97]
I just started to use your Grunt plugins and I'm happy to finaly check my less files for lint.

However, your csslint dependency version is [way out of date](https://david-dm.org/jgable/grunt-lesslint). So, some rules (eg: animation-direction: reverse;) are unknown and raise errors.
I don't know the side effect, so I don't feel confortable doing a PR.

Hope it's possible.

Thanks

**Comment by guoliang** [comment]
Can be closed when #100 is merged
